name: Build

on:
  push:
    branches:
      - "features/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  API_IMAGE: isa-api:sha-${{ github.sha }}
  CLIENT_IMAGE: isa-client:sha-${{ github.sha }}

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build test image
        run: |
          cd api/
          docker build . -t $API_IMAGE

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag container
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: ${{ env.CLIENT_IMAGE }}
          push: false
